### ISSUE TITLE
[ES NumberRange] Format of decimal in Spanish

### ISSUE THREAD

**Issue by HaoYangMS** [Microsoft/Recognizers-Text#1174]
**Describe the bug**
In Spanish parse results, the decimal dot is "," but not ".". The parse result should be independent of languages.

**To Reproduce**
Parse "Este número es más alto que un cuarto y más bajo que un medio."

**Expected result**
```json
{
  "Text": "más alto que un cuarto y más bajo que un medio",
  "TypeName": "numberrange",
  "Resolution": {
    "value": "(0.25,0.5)"
  },
  "Start": 15,
  "End": 60
}
```

**Actual result**
```json
{
  "Text": "más alto que un cuarto y más bajo que un medio",
  "TypeName": "numberrange",
  "Resolution": {
    "value": "(0,25,0,5)"
  },
  "Start": 15,
  "End": 60
}
```

**Comment by tellarin** [comment]
The decimal separator in Spanish depends on Location. For example, it's "," in Spain, but "," in Puerto Rico. Both are supported for tagging/extraction.

The ```value``` field in Resolution however, follows a canonical format. So it's always dot-separated, independently of language or settings. This is a behaviour by design.
 
In some other parts of the recognizers this canonical behaviour is incorrect and it was not yet fixed for compatibility reasons. But a future version of the packages will make all values to be the canonical form. When this is implemented, the packages version will have a bump in major version (semver) to represent the potentially-breaking change.

**Comment by tellarin** [comment]
As NumberRange in Spanish is new, let's add the correct behaviour. #1172 can include it, or it can come in a follow up PR.
For changes in Number/Date, if needed, they should wait until all cultures can change and the version bump happen.

**Comment by HaoYangMS** [comment]
Actually it is hard to just add the correct behavior in Spanish. The code which causes this problem is in BaseNumberRangeParser.cs line 72 and line 73.
``` csharp
var startValueStr = Config.CultureInfo != null ? startValue.ToString(Config.CultureInfo) : startValue.ToString();
var endValueStr = Config.CultureInfo != null ? endValue.ToString(Config.CultureInfo) : endValue.ToString();
```
These two lines of code will generate the corresponding format number according to the corresponding cultureInfo as the parse result.

**Comment by tellarin** [comment]
@HaoYangMS, NumberRange only currently exist in Chinese and English, so modifying that code to make Spanish correct should not cause any side effect.
