### ISSUE TITLE
[Samples] Update BotBuilderRecognizerBot to BotBuilder V4

### ISSUE THREAD

**Issue by iMicknl** [Microsoft/Recognizers-Text#1473]
**Is your feature request related to a problem? Please describe.**
Currently the BotBuilder sample is using the BotBuilder version 3 SDK and not the newest v4 SDK. Many thing have been changed and creating bots using the V4 version is recommended. 

**Describe the solution you'd like**
Refactor the BotBuilder sample to V4

**Describe alternatives you've considered**
Remove the sample and point to one of the prompt samples in [BotBuilder-samples](https://github.com/Microsoft/Botbuilder-samples) or point to the [BotBuilderCommunity prompts](https://github.com/BotBuilderCommunity/botbuilder-community-dotnet/tree/master/libraries/Bot.Builder.Community.Dialogs.Prompts) which use Recognizers-Text.

**Additional context**
BotBuilder V3 also depends on the Chronic library, where V4 just uses the Recognizers-Text library.

**Comment by tellarin** [comment]
@GasparAcevedoZainSouthworks Can you folks take this and make sure all works correctly?

**Comment by GasparAcevedoZainSouthworks** [comment]
OK @tellarin, we will take this Issue.

**Comment by iMicknl** [comment]
@tellarin is it still necessary to have a BotBuilder example in this repository? Aren't the default prompts making use of `Recognizers-Text`? And the `BotBuilder-Community` packages are providing the missing prompts, using `Recognizers-Text`.

**Comment by GasparAcevedoZainSouthworks** [comment]
Hi @iMicknl, @Tellarin
We created the draft PR #1491  which uses BotBuilder v4 and Recognizers in order to update BotBuilderRecognizerBot sample. We created this as a draft because, as @iMicknl said, the Botbuilder-Dotnet prompts use [recognizers-text](https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Prompts/DatetimePrompt.cs#L58), so, in order to have a better sample, we will be refactoring it.

**Comment by ceciliaavila** [comment]
Hi @iMicknl, @tellarin, 
As you mentioned before, BotBuilder default prompts are making use of Recognizers-Text, so we updated the sample in [PR #1491](https://github.com/Microsoft/Recognizers-Text/pull/1491) to use prompts instead of Recognizers.
As this sample no longer includes Recognizers, we consider that it should be moved to BotBuilder-Samples repository.
In Samples repository, there are a few samples that use Prompts but this one, in particular, uses _DateTimePromp_ which we consider it's an interesting one. We could integrate this sample with one of the existing ones leaving a sample with a richer use of Prompts.
Do you agree with this?

**Comment by JuanAr** [comment]
@iMicknl if you agree, can you close this issue?

**Comment by tellarin** [comment]
Closing this as the related PR was merged.
