### ISSUE TITLE
[* DateTime] Inconsistent behaviors among platforms affect order of Resolution values

### ISSUE THREAD

**Issue by STayinloves** [microsoft/Recognizers-Text#1494]
In .NET platform, the order of the elements in `Resolution.values` relied on the order of C# `Dictionary` which is non-deterministic. So its counterpart in other platforms may produce elements in a different order. But the testing code does examine the order of elements in `Resolution.values`.

So two solution may be effective:
- making the order of elements in `Resolution.values` reliable
- let the testing code not check the order (if it isn't necessary)

**Comment by tellarin** [comment]
@Aliandi could you folks help with this? This is a Python issue where the current test code will fail as the order of resolutions may change. We can fix the test code to not rely on the order.
This would allow us to re-enable many Python tests and make sure features work correctly there. Currently many spec cases have their tests disabled due to this.

**Comment by Aliandi** [comment]
Hey @tellarin! Sure we will look into this and let you know. We will be testing using [this](https://github.com/microsoft/Recognizers-Text/blob/a313d3331a4787ccf08093ba64ed6f4bb368dde1/Specs/DateTime/English/DateTimeModel.json#L10848) test, mentioned in the related PR #1543.
