### ISSUE TITLE
[EN Number] Handling "100g" case 

### ISSUE THREAD

**Issue by acblacktea** [microsoft/Recognizers-Text#1859]
Now we get the dimension "100g" in result
![image](https://user-images.githubusercontent.com/17824206/64417370-7ddbb500-d0cb-11e9-9d68-687901884d37.png)

what we expect is get a number 100 in result

**Comment by tellarin** [comment]
Unfortunately, the behaviour of 100g -> unit is by design.
Pre-normalization of the sentence is required to "100 g", so the output would contain both a unit and a number. 
Typically tags shouldn't apply to partial tokens as that causes issues in different pipelines.
There are some situations where this type of mistake currently happens, but we'll remove them in v2.0.
