### ISSUE TITLE
Is there a release roadmap?

### ISSUE THREAD

**Issue by HiltonGiesenow** [microsoft/Recognizers-Text#2515]
**Describe the bug**
There are several recent fixes I'm waiting for since early Jan already, so I'm curious when the next release will be, or if there's some kind of roadmap available? Sorry for raising as a "bug", wasn't sure the best way to ask.

I know I can just reference a build directly, but there's nothing urgent I need so happy to wait for the latest package, just curious when it will be.

**Comment by tellarin** [comment]
Hi @HiltonGiesenow,
.NET releases are currently being pushed out roughly every two months. There should be a release next week (v.1.6.0). 
JavaScript has a slower release rythm and Python/Java are still in alpha.

For open questions, you can use Discussions on GitHub too, instead of Issues. But no worries.
