### ISSUE TITLE
[DateTime2 .NET] tomorrow at 9AM PT results in offset of -420/mountain time  (utc-7) of -480 (-utc8)

### ISSUE THREAD

**Issue by zoinkydoink** [microsoft/Recognizers-Text#2579]
as the title says, it seems to think PT means -7 utc, instead of -8 utc which should be for  pacific time and not mountain time

**Comment by zoinkydoink** [comment]
also `April 29th 11am CST`  does not resolve the timeoffset properly either

**Comment by tellarin** [comment]
PT was mistakenly pointing to PDT instead of PST. This will be fixed in the next update.
CST however, falls into the ambiguous case we discussed some time ago. Currently that's returned as undefined (XX:XX, -1000). Returning a list of the possible offsets is a feature in the roadmaps, but not ETA for its release.
Thanks for the feedback!
