### ISSUE TITLE
[DE] The word gets split in the sentence for a given intent

### ISSUE THREAD

**Issue by fanidamj** [Microsoft/Recognizers-Text#349]
When the input is suche in deutschland, it gets split deutsch land. I've reproduced this issue in eu.luis.ai.

![image](https://user-images.githubusercontent.com/16520557/36294809-0c8f4c4c-1298-11e8-8915-2f402c46b06b.png)

**Comment by tellarin** [comment]
Hi @fanidamj,
this repo is only for the Recognizers-Text project. The issue you're mentioning is a LUIS issue not related to the entity recognizers here.
Perhaps https://github.com/Microsoft/Cognitive-LUIS-Windows or https://github.com/Microsoft/LUIS-Samples would be better places to ask?
I'll close this issue here, ok?
