### ISSUE TITLE
[FR Unit] Several unit issues

### ISSUE THREAD

**Issue by thomasryck** [microsoft/Recognizers-Text#428]
I have some difficulties to recognize units in LUIS. When I add an utterance saying " Il me faut 3 kg de pommes", I get the following label " Il me faut datetimeV2 kg de pommes". 
I have to add an entity in order to be able to extract the unit. 
I got the same kind of issue with other units as square units, cubic units ...

I have also an issue with currency e.g : "3 €" is recognized as a temperature and  "63,45 $" as "number $"

P.S: I have also a side question. Is this repos continously deploy to LUIS ?

**Comment by tellarin** [comment]
@LionbridgeCSII, can you check these?

**Comment by LionbridgeCSII** [comment]
> @LionbridgeCSII, can you check these?

@tellarin, I am unable to reproduce these issues in Visual Studio and in SimpleConsole (.NET and Python). 
But a problem occurs in .NET SimpleConsole with the symbol "€" because expressions like "3 €", "€12"... are not recognized as Currency (but they are recognized in VS). And this happens with all languages, not only French.

**Comment by tellarin** [comment]
> "3 €", "€12"

Is this an encoding issue?

**Comment by tellarin** [comment]
I'll close this issue as the remaining discussion is not specific to it.

**Comment by LionbridgeCSII** [comment]
> Is this perhaps an encoding issue? If so, please open an issue for it.

I was thinking the same, I will open an issue and look into it.
