### ISSUE TITLE
Nonsense result for timezone

### ISSUE THREAD

**Issue by martindevans** [Microsoft/Recognizers-Text#871]
**Describe the bug**
I'm using the latest C# nuget package (1.1.0) to try and extract timezone offsets from input text. With any of the the following input text:

 - `London time`
 - `BST`
 - `New York time`

with the following code:

    var results = DateTimeRecognizer.RecognizeDateTime(input, Culture.English, DateTimeOptions.EnablePreview);

Returns a nonsense result like this:

```
[  
   {  
      "Text":"bst",
      "Start":0,
      "End":2,
      "TypeName":"datetimeV2.timezone",
      "Resolution":{  
         "values":[  
            {  
               "type":"timezone",
               "value":"UTC+XX:XX",
               "utcOffsetMins":"-10000"
            }
         ]
      }
   }
]
```

**Expected behavior**
If a resolution value is created, the `utcOffsetMins` value should be correct.

**Platform (please complete the following information):**
 - Platform: Windows+C#
 - Environment: Visual studio project with `Microsoft.Recognizers.text`, `Microsoft.Recognizers.Text.DateTime` and `Microsoft.Recognizers.Text.DatatTypes.TimexExpression` installed from nuget
 - Version of package `1.1.0` of all three packages

**Comment by tellarin** [comment]
This is by design. Timezone recognition is behind the EnablePreview flag as it's not feature complete.
"UTC+XX:XX" means there are conflicting resolutions or not enough data to resolve. This can happen for ambiguous acronyms (very common), or due to no existing mapping of city/country to timezone.

This design provides value for consumers that only want tagging of timezones or that can call additional services for resolution in the cases mentioned above.

Listing candidate resolutions for ambiguous timezones and providing a way to expand mapping data are features that will come further down the line. The current implementation also has some performance issues to be ironed out before exposed by default.

**Comment by martindevans** [comment]
I don't fully understand the specs/testing process yet, but I'll read up on that and try to get in some PRs to fix these cases. For these particular ones it sounds like it should be relatively simple case of just adding mappings. Thanks for the fast response :)

**Comment by tellarin** [comment]
London and New York time would be simple. 
But "BST" is problematic as it's ambiguous between "British Summer Time", "Bougainville Standard Time", and "Bangladesh Standard Time". A proper fix for that will need to wait until alternative resolutions can be returned. :-/
