### ISSUE TITLE
[EN DateTimeV2.*Range] Last part of a date range is not fully taken into consideration

### ISSUE THREAD

**Issue by gustavocalheiros** [Microsoft/Recognizers-Text#952]
**Describe the bug**
last part of a date range is not fully taken into consideration

**To Reproduce**
- In  C# you type: `from 2015 to 2017`
- you get:

```
{
  "Text": "from 2015 to 2017",
  "Start": 0,
  "End": 16,
  "TypeName": "datetimeV2.daterange",
  "Resolution": {
    "values": [
      {
        "timex": "(2015-01-01,2017-01-01,P2Y)",
        "type": "daterange",
        "start": "2015-01-01",
        "end": "2017-01-01"
      }
    ]
  }
}
```

**Expected behavior**
`"timex": "(2015-01-01,2017-12-31,P3Y)",`

` "end": "2017-12-31"`  (the last year should be fully taken into consideration.).

**Platform**
 - Platform: C#
 - Version of package: 1.1.2

**Additional context**
Happens also with months. 
Logicaly, when dealing with ranges, we always expect that the 2nd part of the range is fully considered.

**Comment by gustavocalheiros** [comment]
or even, taking into consideration the hour in the DateTime object, the expected result should be:
`{01/01/2018 00:00:00}`

**Comment by tellarin** [comment]
Hi @gustavocalheiros,
this behaviour is by design and we currently consider it the best approach from a platform point of view.

As different ways to mention ranges are ambiguous between people (ex: How many year are there between 2002 and 2004? Many people would say 2, some would say 3, a few would say 1), the recognizers treat all ranges the same - as inclusive of the start point (closed) and excluding the endpoint (open). E.g. [start, end).

This allows the recognizers to provide stable and coherent/well-defined behaviour to depend on. Consumers of the output can then decide if they want to re-interpret results in their specific usage scenarios and consider an interval with closed end, or even both ends open. The recognizers can't take that decision as they have no knowledge of usage scenarios.
